CREATE TABLE "requisition_approvals" (
	"id" varchar(24) PRIMARY KEY NOT NULL,
	"requisition_id" varchar(24) NOT NULL,
	"stage" varchar(100) NOT NULL,
	"approver_id" varchar(24) NOT NULL,
	"status" varchar(50) NOT NULL,
	"comments" text,
	"timestamp" timestamp DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "requisition_items" (
	"id" varchar(24) PRIMARY KEY NOT NULL,
	"requisition_id" varchar(24) NOT NULL,
	"item_name" varchar(255) NOT NULL,
	"item_type" varchar(50) NOT NULL,
	"preferred_brand" varchar(255),
	"item_description" text NOT NULL,
	"upload_image" text,
	"units" varchar(50),
	"uom" varchar(50),
	"recommended_vendor_id" varchar(24),
	"is_work_tool" boolean DEFAULT false NOT NULL,
	"status" varchar(50) DEFAULT 'pending',
	"department_approved_by_id" varchar(24),
	"department_approved_at" timestamp,
	"department_rejected_by_id" varchar(24),
	"department_rejected_at" timestamp,
	"department_comments" text,
	"hr_approved_by_id" varchar(24),
	"hr_approved_at" timestamp,
	"hr_rejected_by_id" varchar(24),
	"hr_rejected_at" timestamp,
	"hr_comments" text,
	"hhra_approved_by_id" varchar(24),
	"hhra_approved_at" timestamp,
	"hhra_rejected_by_id" varchar(24),
	"hhra_rejected_at" timestamp,
	"hhra_comments" text,
	"procurement_comments" text,
	"rfq_id" varchar(24),
	"purchase_order_id" varchar(24),
	"created_at" timestamp DEFAULT now() NOT NULL,
	"updated_at" timestamp DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "requisitions" (
	"id" varchar(24) PRIMARY KEY NOT NULL,
	"requisition_number" varchar(100) NOT NULL,
	"title" varchar(255) NOT NULL,
	"urgency" varchar(50),
	"justification" text NOT NULL,
	"delivery_location_id" varchar(24) NOT NULL,
	"delivery_date" timestamp NOT NULL,
	"payment_status" varchar(50) DEFAULT 'unpaid',
	"payment_amount" varchar(50) DEFAULT '0',
	"payment_date" timestamp,
	"payment_reference" varchar(255),
	"payment_notes" text,
	"payment_by_id" varchar(24),
	"requester_id" varchar(24) NOT NULL,
	"department_id" varchar(24) NOT NULL,
	"assigned_approver_id" varchar(24),
	"status" varchar(50) DEFAULT 'draft',
	"request_approved_at" timestamp,
	"po_approved_at" timestamp,
	"additional_info" text,
	"created_at" timestamp DEFAULT now() NOT NULL,
	"updated_at" timestamp DEFAULT now() NOT NULL,
	CONSTRAINT "requisitions_requisition_number_unique" UNIQUE("requisition_number")
);
