CREATE TABLE "comments" (
	"id" varchar(24) PRIMARY KEY NOT NULL,
	"text" text NOT NULL,
	"author_id" varchar(24) NOT NULL,
	"requisition_id" varchar(24),
	"bid_id" varchar(24),
	"parent_comment_id" varchar(24),
	"tagged_users" json,
	"is_deleted" boolean DEFAULT false NOT NULL,
	"deleted_at" timestamp,
	"created_at" timestamp DEFAULT now() NOT NULL,
	"updated_at" timestamp DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "deliveries" (
	"id" varchar(24) PRIMARY KEY NOT NULL,
	"delivery_number" varchar(100) NOT NULL,
	"purchase_order_id" varchar(24) NOT NULL,
	"requisition_id" varchar(24) NOT NULL,
	"vendor_id" varchar(24) NOT NULL,
	"items" json,
	"status" varchar(50) NOT NULL,
	"scheduled_date" timestamp,
	"delivery_date" timestamp,
	"received_by_id" varchar(24),
	"received_at" timestamp,
	"notes" text,
	"tracking_number" varchar(100),
	"carrier" varchar(100),
	"attachments" json,
	"requester_verification" json,
	"hod_approval" json,
	"pm_notification" json,
	"inventory_verification" json,
	"department_verification" json,
	"inventory_confirmation" json,
	"department_confirmation" json,
	"created_at" timestamp DEFAULT now() NOT NULL,
	"updated_at" timestamp DEFAULT now() NOT NULL,
	CONSTRAINT "deliveries_delivery_number_unique" UNIQUE("delivery_number")
);
--> statement-breakpoint
CREATE TABLE "grns" (
	"id" varchar(24) PRIMARY KEY NOT NULL,
	"grn_number" varchar(100) NOT NULL,
	"purchase_order_id" varchar(24) NOT NULL,
	"requisition_id" varchar(24) NOT NULL,
	"items" json,
	"general_remarks" text,
	"created_by_id" varchar(24) NOT NULL,
	"receiver_id" varchar(24) NOT NULL,
	"approvals" json,
	"status" varchar(50) NOT NULL,
	"delivered_at" timestamp,
	"created_at" timestamp DEFAULT now() NOT NULL,
	"updated_at" timestamp DEFAULT now() NOT NULL,
	CONSTRAINT "grns_grn_number_unique" UNIQUE("grn_number")
);
--> statement-breakpoint
CREATE TABLE "jcfs" (
	"id" varchar(24) PRIMARY KEY NOT NULL,
	"jcf_number" varchar(100) NOT NULL,
	"purchase_order_id" varchar(24) NOT NULL,
	"requisition_id" varchar(24) NOT NULL,
	"vendor_id" varchar(24) NOT NULL,
	"created_by_id" varchar(24) NOT NULL,
	"approver_id" varchar(24),
	"service_description" text,
	"completion_evidence" text,
	"rating" varchar(20),
	"status" varchar(50) NOT NULL,
	"approval" json,
	"attachments" json,
	"pdf_url" text,
	"completed_at" timestamp,
	"created_at" timestamp DEFAULT now() NOT NULL,
	"updated_at" timestamp DEFAULT now() NOT NULL,
	CONSTRAINT "jcfs_jcf_number_unique" UNIQUE("jcf_number")
);
--> statement-breakpoint
CREATE TABLE "notifications" (
	"id" varchar(24) PRIMARY KEY NOT NULL,
	"type" varchar(100) NOT NULL,
	"actor_id" varchar(24) NOT NULL,
	"actor_model" varchar(50) DEFAULT 'User' NOT NULL,
	"recipient_id" varchar(24) NOT NULL,
	"recipient_model" varchar(50) DEFAULT 'User' NOT NULL,
	"resource_kind" varchar(50) NOT NULL,
	"resource_id" varchar(24) NOT NULL,
	"comment_id" varchar(24),
	"metadata" json,
	"is_read" boolean DEFAULT false NOT NULL,
	"created_at" timestamp DEFAULT now() NOT NULL,
	"updated_at" timestamp DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "purchase_orders" (
	"id" varchar(24) PRIMARY KEY NOT NULL,
	"po_number" varchar(100) NOT NULL,
	"title" varchar(255),
	"requisition_id" varchar(24) NOT NULL,
	"rfq_id" varchar(24),
	"vendor_id" varchar(24) NOT NULL,
	"items" json,
	"subtotal" varchar(50),
	"discount" varchar(50),
	"discount_type" varchar(50),
	"discount_amount" varchar(50),
	"vat" varchar(50),
	"vat_rate" varchar(50),
	"vat_amount" varchar(50),
	"total_amount" varchar(50) NOT NULL,
	"total_price" varchar(50),
	"delivery_location_id" varchar(24) NOT NULL,
	"delivery_date" timestamp NOT NULL,
	"delivery_contact_id" varchar(24),
	"delivery_address_snapshot" json,
	"shipping" varchar(255),
	"general_terms" text,
	"evaluation_criteria" text,
	"terms_of_service" text,
	"payment_terms" text,
	"quote_url" text,
	"vendor_quote" text,
	"vendor_quotes" json,
	"approvals" json,
	"status" varchar(50) DEFAULT 'draft' NOT NULL,
	"created_by_id" varchar(24) NOT NULL,
	"submitted_by_id" varchar(24),
	"submitted_at" timestamp,
	"pdf_url" text,
	"service_classification_override" text,
	"service_classification_reason" text,
	"created_at" timestamp DEFAULT now() NOT NULL,
	"updated_at" timestamp DEFAULT now() NOT NULL,
	CONSTRAINT "purchase_orders_po_number_unique" UNIQUE("po_number")
);
--> statement-breakpoint
CREATE TABLE "rfq_items" (
	"id" varchar(24) PRIMARY KEY NOT NULL,
	"rfq_id" varchar(24) NOT NULL,
	"item_id" varchar(24) NOT NULL,
	"item_description" text NOT NULL,
	"detailed_specification" text NOT NULL,
	"uom" varchar(50) NOT NULL,
	"quantity" varchar(50) NOT NULL,
	"expected_delivery_date" timestamp NOT NULL,
	"quoted_unit_price" varchar(50),
	"quoted_total_price" varchar(50),
	"vendor_comments" text,
	"created_at" timestamp DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "rfqs" (
	"id" varchar(24) PRIMARY KEY NOT NULL,
	"rfq_number" varchar(100) NOT NULL,
	"title" varchar(255) NOT NULL,
	"requisition_id" varchar(24) NOT NULL,
	"vendors" json,
	"vendor_id" varchar(24),
	"related_pos" json,
	"evaluation_criteria" text,
	"terms_and_conditions" text,
	"delivery_location_id" varchar(24) NOT NULL,
	"expected_delivery_date" timestamp,
	"status" varchar(50) DEFAULT 'draft' NOT NULL,
	"created_by_id" varchar(24) NOT NULL,
	"issued_at" timestamp,
	"quote_received_at" timestamp,
	"quote_document" text,
	"quote_total_amount" varchar(50),
	"quote_valid_until" timestamp,
	"quote_notes" text,
	"created_at" timestamp DEFAULT now() NOT NULL,
	"updated_at" timestamp DEFAULT now() NOT NULL,
	CONSTRAINT "rfqs_rfq_number_unique" UNIQUE("rfq_number")
);
--> statement-breakpoint
CREATE TABLE "vendors" (
	"id" varchar(24) PRIMARY KEY NOT NULL,
	"name" varchar(255) NOT NULL,
	"contact_person" varchar(255) NOT NULL,
	"contact_person_designation" varchar(255),
	"email" varchar(255) NOT NULL,
	"phone" varchar(50) NOT NULL,
	"address" text NOT NULL,
	"website" varchar(255),
	"date_of_incorporation" timestamp,
	"categories" json,
	"documents" json,
	"cac_document" json,
	"rating" varchar(20),
	"is_verified" boolean DEFAULT false NOT NULL,
	"is_active" boolean DEFAULT true NOT NULL,
	"status" varchar(50) DEFAULT 'pending' NOT NULL,
	"created_at" timestamp DEFAULT now() NOT NULL,
	"updated_at" timestamp DEFAULT now() NOT NULL,
	CONSTRAINT "vendors_email_unique" UNIQUE("email")
);
